### ISSUE TITLE
Not showing clear icon when apply to AlertDialog

### ISSUE THREAD

**Issue by plugie** [kopihao/KopihaoClearableEditText#1]
is clearableedittext working inside AlertDialog ?

With below code, the clear icon is not shown and so I  can't clear the text

AlertDialog.Builder builder=new AlertDialog.Builder(this);
View form = getLayoutInflater().inflate(R.layout.main_dialog, null);
ClearableEditText etSellPrice = (ClearableEditText) form.findViewById(R.id.editTextItemSellPrice);

**Comment by kopihao** [comment]
Yes. I will provide an example to demo its implementation within AlertDialog. 
If the issue persists, don't hesitate to contact me again.
Thanks for the comment :) 

 ![screenshot_2015-12-28-03-18-13](https://cloud.githubusercontent.com/assets/8252002/12011640/afccbd84-ad11-11e5-8dba-44bc8aca0e4b.jpeg)

![screenshot_2015-12-28-03-16-08](https://cloud.githubusercontent.com/assets/8252002/12011633/7a8df11a-ad11-11e5-8092-9846412c2bd1.jpeg)

**Comment by plugie** [comment]
Thanks a lot. 
I use table layout and use stretchColumns for ClearableEditText. 
After I use layout_weight="1.0" the clear icon is shown.

Below is the code for main_dialog.xml

```
    <?xml version="1.0" encoding="utf-8"?>
    <TableLayout xmlns:android="http://schemas.android.com/apk/res/android"
                 android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:stretchColumns="2">
         <TableRow
               android:layout_marginLeft="10dp"
               android:layout_marginRight="10dp"
              android:layout_marginTop="5dp">

    <TextView
        android:id="@+id/textViewItemSellDesc"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:gravity="left"
        android:text="Price" />

    <TextView
        android:id="@+id/textViewItemSellColon"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginLeft="10dp"
        android:layout_marginRight="5dp"
        android:gravity="left"
        android:text=":" />

            <com.view.plugin.cet.ClearableEditText
            android:id="@+id/editTextItemSellPrice"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_weight="1.0"/> <!-- Need to add this property to make icon clear is shown -->
            </TableRow>
    </TableLayout>
```

**Comment by kopihao** [comment]
Glad to hear that. 
If you encounter any anomaly or having idea to improve this plugin, don't hesitate to contact me :)
